### ISSUE TITLE
6LNT

### ISSUE THREAD

**Issue by RudoRoemer** [DisQS/animol-viewer#1]
This is a problem with the display of PDB structure 6LNT. See screenshot and structure files as enclosed (or download from PDB at https://www.rcsb.org/structure/6LNT
![2021-11-28](https://user-images.githubusercontent.com/7069514/143781012-7355cafc-172a-4ae2-a6be-e367625a1532.png)
).

**Comment by RudoRoemer** [comment]
See also 3CSY, i.e. https://www.rcsb.org/structure/3csy, 
![2021-11-28 (1)](https://user-images.githubusercontent.com/7069514/143781230-7704bef2-8fcc-4780-a0af-73cfe3f4026e.png)

**Comment by james-panayis** [comment]
Hmmm, interesting. At a glance, this seems to be things wrapping due to exceeding the bounds of the coordinate system. Something's probably being scaled wrongly somewhere...

**Comment by james-panayis** [comment]
This is now fixed, and will be fixed in a more scalable way soon
